name: Matrix Job Workflow

on: 
  workflow_dispatch: 
    inputs:
      json_input:
        description: 'Input JSON to start the recursive workflow'
        required: true
        type: string

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger First Level
        uses: kamilchodola/test_dynamic_workflows/.github/workflows/resursive.yml@main
        with:
          json: ${{ github.event.inputs.json_input }}
