name: Matrix Job Workflow

on: 
  workflow_dispatch: 

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read the JSON file and create matrix
        id: set-matrix
        run: |
          jobs=$(cat .github/workflows/jobs.json | jq '.' )
          echo "matrix=$jobs" >> $GITHUB_OUTPUT
          echo $jobs

  dynamic-jobs:
    needs: generate-matrix
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.job.runs_on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Set up GitHub CLI with GITHUB_TOKEN
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Wait and Download Artifacts for Dependencies
        if: ${{ matrix.job.dependencies && matrix.job.dependencies != '' }}
        env:
          DEPENDENCIES_JSON: ${{ toJson(matrix.job.dependencies) }}
        run: python wait_and_download.py

      - name: Run Job Logic
        run: |
          echo "Running ${matrix.job.name} with input from dependencies"
          cat artifacts/*

      - name: Save Job Output
        run: |
          echo "${matrix.job.name} output" > output.txt

      - name: Upload Job Output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job.name }}-output
          path: output.txt
