name: Recursive

on:
  workflow_call:
    inputs:
      json_input:
        required: true
        type: string

jobs:
  start:
    runs-on: ubuntu-latest
    outputs:
      depth: ${{ steps.check.outputs.depth }}
      reduced_json: ${{ steps.check.outputs.reduced_json }}
    steps:
      - name: Do action
        run: echo "Action on input '${{ github.event.inputs.json_input }}'"

      - name: Set input JSON
        id: json-input
        run: echo '${{ github.event.inputs.json_input }}' > input.json

      - name: Check JSON Depth and Reduce
        id: check
        run: |
          DEPTH=$(jq -c '[paths(scalars) | length] | max' input.json)
          REDUCED_JSON=$(jq '.[keys[0]]' input.json)
          echo "depth=$DEPTH" >> $GITHUB_OUTPUT
          echo "reduced_json=$REDUCED_JSON" >> $GITHUB_OUTPUT
          echo "Depth: $DEPTH"
          echo "Reduced JSON: $REDUCED_JSON"

  retrigger:
    needs: [start]
    if: ${{ needs.check-json-depth.outputs.depth > 1 }}
    name: Trigger
    uses: kamilchodola/test_dynamic_workflows/.github/workflows/recursive.yml@main
    with:
      json: ${{ needs.check-json-depth.outputs.reduced_json }}
